### ISSUE TITLE
change timezone to egypt 

### ISSUE THREAD

**Issue by abdo1819** [abdo1819/server_evilcar#1]
when viewing violation data it give time at Greenwich 
change it to egypt

**Comment by ak-seyam** [comment]
greenwich was the excepted and ,i think, is the right behavior this must be handled by server admins not by us

**Comment by ak-seyam** [comment]
i don't know if I have access to the application dashboard in herku but if i'm not i think this would be helpful anyway
https://dev.to/paulasantamaria/change-the-timezone-on-a-heroku-app-2b4
